app:
  build: .
  links:
    - redis
  ports:
    - 3000:3000
  environment:
    - HOST=0.0.0.0
    - PORT=3000
    - REDIS_HOST=redis
    - REDIS_PORT=6379

redis:
  image: redis:latest
  ports:
    - 6379
